# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20170106_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.FileField(default='none', upload_to='documents/%Y/%m/%d'),
        ),
    ]
