# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_profileuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='last_name',
        ),
    ]
