# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20170106_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.FileField(default='none', upload_to='avatars'),
        ),
    ]
